image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pnpm install
      pnpm build 
      pnpm build-dev-tools 
      pnpm test
    command: |
      pnpm build
      
ports:
  - name: sync
    port: 8080
    onOpen: ignore
